rabbitvcs/rabbitvcs

rabbitvcs/util/configspec/configspec.ini
rabbitvcs/util/contextmenu.py

Hiding chosen context menu elements was requested long time ago, but seems like hasn't been implemented. This is a simple functionality based on config file. User can create additional section called [HideItem] and specify which items needs to be hidden.
I am sorry if the code isn't too professional, I'm just a "part time" python dev ;).

New feature: hide context menu items

---

setup.py

command gtk-update-icon-cache does not exist. Changed it to gtk-update-icon-cache-3.0.

Ubuntu 14.10 install fix

---

rabbitvcs/util/helper.py
rabbitvcs/vcs/svn/__init__.py

Greetings!
I'm not quite sure, how our team managed to get the following result while using svn, maybe one of the build scripts caused it, nevertheless there occured to be an _empty_ commit in our log. Not with the author empty, but with the date also.
Not a great problem at all really, but it caused my favourite RabbitVCS to fail on "Show log", displaying the following error (pic. 1). I got the nerve to offer you a small commit, which fixes it instead of bothering you with such a minor issue.
The solution is based on my belief that no other commit could be dated with 1900 year. The output matches the similar of the console svn (pic. 2). 
**Before:**
**After:**
Accept it, if you find it worthy. 
With best regards

minor fix: commits without date specified are shown correctly

---

rabbitvcs/ui/widget.py

A feature I missed very much from TortoiseSVN / TortoiseGit was the ability to ctrl+click select a range of files, then click the checkbox and select them all for commit.  This enables that functionality in RabbitVCS.  See comments for an explanation of the implementation.

Implemented multi-check

---

rabbitvcs/util/helper.py

A solution for https://github.com/rabbitvcs/rabbitvcs/issues/149 . Now, you can create this desktop file on Ubuntu:
```
[Desktop Entry]
Encoding=UTF-8
Name=RabbitVCS
Exec=rabbitvcs browser
Icon=rabbitvcs
Categories=Application;Development;
Type=Application
StartupNotify=true
StartupWMClass=RabbitVCS
Terminal=0
```
and have all RabbitVCS windows grouped below it.

Add support for Ubuntu sidebar window grouping.

---

rabbitvcs/vcs/git/gittyup/client.py

When filename contains special latin characters, git commands return filenames encoded, so any further operation fails :
$ git status --porcelain
?? "TEST_\304\205\305\202\303\263\305\2721.txt"
to properly operate we need to decode this strings and remove quotation marks

GIT - fix working with polish characters in filenames

---

rabbitvcs/vcs/git/gittyup/client.py

GIT-Stage should always operate on relative path.
Currently when operating on absolute path cause problem when commiting edited files

GIT: stage always relative path

---

rabbitvcs/services/checkerservice.py

Now checker process can be auto-started when checker-service will be down

fix auto-start service when checkerservice was killed

---

rabbitvcs/ui/commit.py

Fix for issue https://github.com/rabbitvcs/rabbitvcs/issues/167
Add showing branch name in commit dialog

#167 - GIT: Add showing branch name in commit dialog

---

rabbitvcs/ui/clone.py

Added a feature to the Clone dialog to set the default url to the value in the clipboard (for `.git` urls).
This feature allows the user to copy a repo url from Github, etc and have the Clone dialog default to this url.

Set clone dialog Url to value in clipboard.

---

rabbitvcs/vcs/git/gittyup/client.py

This fix resolves the issue of the promptUsername dialog not working correctly.
*When clicking `OK` in the above dialog, nothing would happen, forcing the user to click `Cancel`. This fix resolves the issue.*

Fixed typo in promptUsername for push/pull/clone dialog.

---

setup.py

Solve an error with not existing configspec.ini during install on Debian system. See issue #241 about details.

Solve configspec.ini not existing during install on Debian

---

README.md

Please read the note. It is related to the code at launch_ui_window() function. I wasted my childhood years trying to figure out why I can't see my svn history and I refuse to waste my retirement years trying to figure out how the svn command line works. :D

Add note for env PYTHON variable

---

clients/pluma/README
clients/pluma/rabbitvcs-plugin.py
clients/pluma/rabbitvcs-pluma.plugin

Hi Adam,
This PR implements a RabbitVCS Pluma client. I've derived and adapted it from the (now broken) gedit client.
I've tested it successfully with Pluma 1.20.2 (Python 2.7) and a Python 3 version of Pluma (from git master) I'm currently working on.
Unfortunately, it still uses deprecated Gtk.Action, Gtk.ActionGroup and Gtk.UIManager, as Pluma requires them.
Regards,
Patrick

New Pluma client

---

rabbitvcs/ui/log.py

This fixes a bug when selecting a revision from the log dialog (for example, when merging a range of revisions in SVN), which did not fill the "Revision range" input with the selected revisions.

Fix revision selection not working in log dialog

---

rabbitvcs/ui/editconflicts.py

In conflict editing, revision numbers (which are taken from filenames) were compared as strings, which meant that a conflict betwen `r99` and `r100` would treat `r100` as the common ancestor and `r99` as "theirs".

Compare revision numbers as ints not strings

---

rabbitvcs/ui/log.py

When activating the os dark mode, the text color for the log window became the same as the window color. Now it should be correct in both modes.

Fix log window text color for os dark mode

---

rabbitvcs/ui/log.py

Related #307
When the keyboard button up/down was used to navigate the revisions table. The paths table was not updated.

Fix keyboard button up/down handling

---

clients/nautilus/RabbitVCS.py

Setting the emblem on a item in the directory would cause a invalidation of the item_cache, causing a re-scan of the item. This is not needed as the item did not really change.

Prevent double scanning all version controlled items in a directory (speed up nautilus)

---

rabbitvcs/ui/log.py

The cursor-changed callback was missing for the git revisions_table, so the paths_table ("Affected files") was never updated.

Add missing cursor-changed callback for git revisions_table

---

setup.py

Module distutils is deprecated and will be dropped out in Python 3.12: its use should be replaced by setuptools.
This commit converts rabbitvcs `setup.py` to use setuptools rather than distutils, in a nearly compatible way.
Note that used keyword `data_files` is deprecated and not replaced. It is however still operational.
IMO a new setup strategy ought to be implemented for rabbitvcs setup, but this is out of my skill.
in the meantime, this commit will allow the project's setup to survive some time.
Feedbacks and comments welcomed.

setup: use setuptools

---

rabbitvcs/util/helper.py

patch doesn't support CRLF line endings on Linux, so when I modified such a file and ran "rabbitvcs checkmods", patch silently failed and meld showed "These files are identical".
Instead of copying the working files to /tmp, running svn diff between the working copy and its base, and then reverse patching the tmp files for comparison, it works to svn export the base to /tmp.

svn-export instead of cp/svn-diff/patch

---

rabbitvcs/vcs/git/gittyup/client.py

https://github.com/rabbitvcs/rabbitvcs/issues/319
soft or hard reset in git results in following error message: `fatal: Cannot do hard reset with paths`
deleting the path from reset window instead gives an error `fatal: ../..: '../..' is outside repository`
this change always omits paths for hard and soft resets which is what is supposed to happen

fix git soft and hard reset

---

rabbitvcs/vcs/git/gittyup/client.py

Deletion command removed file indices causing files to marked as missing - not existing but not staged either, as if erroneously removed by shell `rm FILENAME` command
This was changed to deleting the file from filesystem and then staging that non-existing file - which causes git to properly mark the file for deletion from the repository branch upon commit - as if shell command `git rm FILENAME` was executed

fix git file deletion

---

rabbitvcs/ui/annotate.py
rabbitvcs/vcs/svn/__init__.py

Use annotate2 API from pysvn (available since SVN 1.7 from 2011): https://pysvn.sourceforge.io/Docs/pysvn_prog_ref.html#pysvn_client_annotate2
No need to parse date string twice anymore, as log is retrieved and parsed anyway.

SVN: Use annotate2 API
